{{- if and .Values.lightning_features.secure_lightning.ctf .Values.enbuildCTF.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-enbuild-ctf
  labels:
    app: ctf
    app.kubernetes.io/component: ctf
  {{- include "enbuild-helm-chart.labels" . | nindent 4 }}
  {{- with .Values.enbuildCTF.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
